#!/bin/sh


PATH=/opt/wine-stable/bin:$PATH
WINE="wine"
WINPYTHONDIR="C:\\\Miniconda3"
PYINSTALLER="$WINPYTHONDIR/Scripts\\\pyinstaller.exe"
PYTHON="$WINPYTHONDIR/pythonw.exe"
SCRIPT="visualbond"

echo $PYTHON

rm -R dist
rm -R build

$WINE $PYTHON setup.py install 
$WINE $PYINSTALLER   --add-data "spectrojotometer/logo.gif;spectrojotometer" -i "spectrojotometer.ico"  -w -D  bin/visualbond.py 
#$WINE $PYINSTALLER  -D   bin/$SCRIPT.py 

echo "      "
echo "      "
echo "  Test running the application    "
echo "      "
echo "      "

#$WINE dist/$SCRIPT/$SCRIPT.exe

echo "      "
echo "      "
echo "  Zipping application    "
echo "      "
echo "      "

cd dist
cp  ../api-*.dll $SCRIPT
cp -R ../examples $SCRIPT
zip -r "$SCRIPT.zip"  $SCRIPT

cd ..
